# see https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

run:
  tests: true
  modules-download-mode: readonly

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - gocritic
    - gocyclo
    - gosec
    - govet
    - importas
    - intrange
    - lll
    - makezero
    - mirror
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - sloglint
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - wrapcheck
    - whitespace

  settings:
    govet:
      enable-all: true

    gosec:
      excludes:
        - G101 # Look for hard coded credentials, this linter is dumb

    importas:
      no-unaliased: true

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint

    gocyclo:
      min-complexity: 15

    lll:
      line-length: 140

    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true

    exhaustive:
      check:
        - switch
        - map

    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "github.com/example/example"
              desc: cannot be imported

    mnd:
      ignored-functions:
        - '^misc\.Seconds'
        - '^misc\.Minutes'
        - '^misc\.Hours'
        - '^misc\.Days'
        - '^(wg|wait|waitGroup)\.Add'
        - "^make"
        - "^os.OpenFile"

    funlen:
      ignore-comments: true

    varnamelen:
      ignore-decls:
        - i int
        - i uint8
        - t testing.T
        - b testing.B
        - e error
        - T any
        - m map[string]int
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true

    wrapcheck:
      ignore-package-globs:
        - golang.org/x/sync/*
        - github.com/rthomazel/go/misc*

    staticcheck:
      checks:
        - all

    whitespace:
      # Enforces newlines (or comments) after every multi-line if statement.
      multi-if: true
      # Enforces newlines (or comments) after every multi-line function signature.
      multi-func: true
