# see https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

run:
  tests: true
  modules-download-mode: readonly

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - funcorder
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocognit
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - lll
    - maintidx
    - mirror
    - misspell
    - modernize
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - predeclared
    - protogetter
    - sloglint
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl_v5
    # - depguard

  settings:
    govet:
      enable-all: true

    gosec:
      excludes:
        - G101 # Look for hard coded credentials, this linter is dumb

    importas:
      no-unaliased: true

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint

    gocyclo:
      min-complexity: 15

    lll:
      line-length: 140

    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true

    exhaustive:
      check:
        - switch
        - map

    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "github.com/example/example"
              desc: cannot be imported

    mnd:
      ignored-functions:
        - '^misc\.Seconds'
        - '^misc\.Minutes'
        - '^misc\.Hours'
        - '^misc\.Days'
        - '^(wg|wait|waitGroup)\.Add'
        - "^make"
        - "^os.OpenFile"

    funlen:
      ignore-comments: true

    varnamelen:
      ignore-decls:
        - i int
        - i uint8
        - t testing.T
        - b testing.B
        - e error
        - T any
        - m map[string]int
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true

    wrapcheck:
      ignore-package-globs:
        - golang.org/x/sync/*
        - github.com/rthomazel/go/misc*

    staticcheck:
      checks:
        - all

    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      case-max-lines: 0
      default: "none" # Can be `all`, `none`, `default` or empty
      enable:
        - append
        - assign
        - branch
        - decl
        - defer
        - err
        - expr
        - for
        - go
        - if
        - inc-dec
        - label
        - range
        - return
        - select
        - send
        - switch
        - type-switch
        - leading-whitespace
        - trailing-whitespace
        - after-block
        - assign-expr
      disable:
        - assign-exclusive
