with-expecter: True
inpackage: True
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
include-regex: ".*"
exclude-regex: "^lookupEnv$"
packages:
  github.com/rthomazel/go/httpmisc:
  github.com/rthomazel/go/misc:
