template: testify
inpackage: True
dir: "{{.InterfaceDir}}"
structname: "Mock{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
include-interface-regex: ".*"
exclude-interface-regex: "^lookupEnv$"
packages:
  github.com/rthomazel/go/httpmisc:
  github.com/rthomazel/go/misc:
